//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightersForm
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FightHistories
    {
        [Key]
        public string Bet { get; set; }
        public string FirstFighterId { get; set; }
        public string SecondFighterId { get; set; }
        public string WinnerId { get; set; }
    }
}
